#!/usr/bin/env bash
BASEDIR=$(dirname $0)
ABSPATH=$(readlink -f $0)
ABSDIR=$(dirname $ABSPATH)

OSUDPD=nil
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
    --user) OSUDPD=t; shift ;;
    *)      POSITIONAL+=("$1"); shift ;;
esac
done

# NOTE: you must set --eval directly
# it cannot be passed in as a ${VAR}
# otherwise emacs will throw a fit

emacs \
    --batch \
    --quick \
    --eval "(setq orgstrap-use-default-package-dir ${OSUDPD})" \
    --load "${ABSDIR}/init.el" \
    --eval "(use-packages ${POSITIONAL[*]})" \
    --kill
