#!/usr/bin/env sh
BASEDIR=$(dirname $0)
ABSPATH=$(readlink -f $0)
ABSDIR=$(dirname $ABSPATH)

OSUDPD=nil
while [ $# -gt 0 ]; do
    case $1 in
        --user) OSUDPD=t ;;
        *)      POSITIONAL="${POSITIONAL} $1" ;;
    esac
    shift
done

# NOTE: you must set --eval directly
# it cannot be passed in as a ${VAR}
# otherwise emacs will throw a fit

emacs \
    --batch \
    --quick \
    --eval "(setq orgstrap-use-default-package-dir ${OSUDPD})" \
    --load "${ABSDIR}/init.el" \
    --eval "(use-packages ${POSITIONAL})" \
    --kill
